<a href="https://colab.research.google.com/github/DakshTomar0223/ml_revision_checklist/blob/main/LogisticRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import fetch_openml

In [2]:
titanic_data = sns.load_dataset('titanic')

In [3]:
df = titanic_data.drop('survived', axis=1).copy()

In [4]:
y = titanic_data['survived'].copy()

In [5]:
df

,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [6]:
df['family'] = df['sibsp'] + df['parch']
df.loc[df['family'] > 0, 'travelled_alone'] = 0
df.loc[df['family']==0, 'travelled_alone'] = 1
df['family'].head()

0    1
1    1
2    0
3    1
4    0
Name: family, dtype: int64

In [7]:
df.drop(['sibsp','parch'],axis=1, inplace = True)

In [8]:
df

,pclass,sex,age,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,family,travelled_alone
0,3,male,22.0,7.2500,S,Third,man,True,NaN,Southampton,no,False,1,0.0
1,1,female,38.0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,1,0.0
2,3,female,26.0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,0,1.0
3,1,female,35.0,53.1000,S,First,woman,False,C,Southampton,yes,False,1,0.0
4,3,male,35.0,8.0500,S,Third,man,True,NaN,Southampton,no,True,0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,2,male,27.0,13.0000,S,Second,man,True,NaN,Southampton,no,True,0,1.0
887,1,female,19.0,30.0000,S,First,woman,False,B,Southampton,yes,True,0,1.0
888,3,female,NaN,23.4500,S,Third,woman,False,NaN,Southampton,no,False,3,0.0
889,1,male,26.0,30.0000,C,First,man,True,C,Cherbourg,yes,True,0,1.0
890,3,male,32.0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True,0,1.0

In [9]:
from sklearn.impute import SimpleImputer
imp_mean = SimpleImputer(strategy = 'mean')

In [10]:
df['age'] = imp_mean.fit_transform(df[['age']])
df['fare'] = imp_mean.fit_transform(df[['fare']])

In [11]:
imp_freq = SimpleImputer(strategy = 'most_frequent')

In [12]:
df['embarked']= imp_freq.fit_transform(df[['embarked']]).flatten()

In [13]:
embark = pd.get_dummies(df['embarked'], drop_first=True)
embark

         Q      S
0    False   True
1    False  False
2    False   True
3    False   True
4    False   True
..     ...    ...
886  False   True
887  False   True
888  False   True
889  False  False
890   True  False

[891 rows x 2 columns]

In [14]:
df = pd.concat([df, embark], axis=1)
df.drop(['embarked'], axis=1, inplace=True)

In [15]:
df

,pclass,sex,age,fare,class,who,adult_male,deck,embark_town,alive,alone,family,travelled_alone,Q,S
0,3,male,22.000000,7.2500,Third,man,True,NaN,Southampton,no,False,1,0.0,False,True
1,1,female,38.000000,71.2833,First,woman,False,C,Cherbourg,yes,False,1,0.0,False,False
2,3,female,26.000000,7.9250,Third,woman,False,NaN,Southampton,yes,True,0,1.0,False,True
3,1,female,35.000000,53.1000,First,woman,False,C,Southampton,yes,False,1,0.0,False,True
4,3,male,35.000000,8.0500,Third,man,True,NaN,Southampton,no,True,0,1.0,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,2,male,27.000000,13.0000,Second,man,True,NaN,Southampton,no,True,0,1.0,False,True
887,1,female,19.000000,30.0000,First,woman,False,B,Southampton,yes,True,0,1.0,False,True
888,3,female,29.699118,23.4500,Third,woman,False,NaN,Southampton,no,False,3,0.0,False,True
889,1,male,26.000000,30.0000,First,man,True,C,Cherbourg,yes,True,0,1.0,False,False
890,3,male,32.000000,7.7500,Third,man,True,NaN,Queenstown,no,True,0,1.0,True,False

In [16]:
df.drop(['embark_town'], axis=1, inplace=True)
display(df.head())

,pclass,sex,age,fare,class,who,adult_male,deck,alive,alone,family,travelled_alone,Q,S
0,3,male,22.0,7.2500,Third,man,True,NaN,no,False,1,0.0,False,True
1,1,female,38.0,71.2833,First,woman,False,C,yes,False,1,0.0,False,False
2,3,female,26.0,7.9250,Third,woman,False,NaN,yes,True,0,1.0,False,True
3,1,female,35.0,53.1000,First,woman,False,C,yes,False,1,0.0,False,True
4,3,male,35.0,8.0500,Third,man,True,NaN,no,True,0,1.0,False,True

In [17]:
df['sex'] = df['sex'].map({'male': 0, 'female': 1})
df['adult_male'] = df['adult_male'].astype(int)
df['alone'] = df['alone'].astype(int)
df['alive'] = df['alive'].map({'no': 0, 'yes': 1})
display(df.head())

,pclass,sex,age,fare,class,who,adult_male,deck,alive,alone,family,travelled_alone,Q,S
0,3,0,22.0,7.2500,Third,man,1,NaN,0,0,1,0.0,False,True
1,1,1,38.0,71.2833,First,woman,0,C,1,0,1,0.0,False,False
2,3,1,26.0,7.9250,Third,woman,0,NaN,1,1,0,1.0,False,True
3,1,1,35.0,53.1000,First,woman,0,C,1,0,1,0.0,False,True
4,3,0,35.0,8.0500,Third,man,1,NaN,0,1,0,1.0,False,True

In [18]:
df['class'] = df['class'].map({'First': 1, 'Second': 2, 'Third': 3})
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['who'] = le.fit_transform(df['who'])
display(df.head())

,pclass,sex,age,fare,class,who,adult_male,deck,alive,alone,family,travelled_alone,Q,S
0,3,0,22.0,7.2500,3,1,1,NaN,0,0,1,0.0,False,True
1,1,1,38.0,71.2833,1,2,0,C,1,0,1,0.0,False,False
2,3,1,26.0,7.9250,3,2,0,NaN,1,1,0,1.0,False,True
3,1,1,35.0,53.1000,1,2,0,C,1,0,1,0.0,False,True
4,3,0,35.0,8.0500,3,1,1,NaN,0,1,0,1.0,False,True

In [19]:
df['deck'] = df['deck'].cat.add_categories('U').fillna('U')
df['deck'] = le.fit_transform(df['deck'])
display(df.head())

,pclass,sex,age,fare,class,who,adult_male,deck,alive,alone,family,travelled_alone,Q,S
0,3,0,22.0,7.2500,3,1,1,7,0,0,1,0.0,False,True
1,1,1,38.0,71.2833,1,2,0,2,1,0,1,0.0,False,False
2,3,1,26.0,7.9250,3,2,0,7,1,1,0,1.0,False,True
3,1,1,35.0,53.1000,1,2,0,2,1,0,1,0.0,False,True
4,3,0,35.0,8.0500,3,1,1,7,0,1,0,1.0,False,True

In [20]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   pclass           891 non-null    int64
 1   sex              891 non-null    int64
 2   age              891 non-null    float64
 3   fare             891 non-null    float64
 4   class            891 non-null    category
 5   who              891 non-null    int64
 6   adult_male       891 non-null    int64
 7   deck             891 non-null    int64
 8   alive            891 non-null    int64
 9   alone            891 non-null    int64
 10  family           891 non-null    int64
 11  travelled_alone  891 non-null    float64
 12  Q                891 non-null    bool
 13  S                891 non-null    bool
dtypes: bool(2), category(1), float64(3), int64(8)
memory usage: 79.4 KB
None

In [21]:
df['Q'] = df['Q'].astype(int)
df['S'] = df['S'].astype(int)

print(df.info())
display(df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   pclass           891 non-null    int64
 1   sex              891 non-null    int64
 2   age              891 non-null    float64
 3   fare             891 non-null    float64
 4   class            891 non-null    category
 5   who              891 non-null    int64
 6   adult_male       891 non-null    int64
 7   deck             891 non-null    int64
 8   alive            891 non-null    int64
 9   alone            891 non-null    int64
 10  family           891 non-null    int64
 11  travelled_alone  891 non-null    float64
 12  Q                891 non-null    int64
 13  S                891 non-null    int64
dtypes: category(1), float64(3), int64(10)
memory usage: 91.6 KB
None

,pclass,sex,age,fare,class,who,adult_male,deck,alive,alone,family,travelled_alone,Q,S
0,3,0,22.0,7.2500,3,1,1,7,0,0,1,0.0,0,1
1,1,1,38.0,71.2833,1,2,0,2,1,0,1,0.0,0,0
2,3,1,26.0,7.9250,3,2,0,7,1,1,0,1.0,0,1
3,1,1,35.0,53.1000,1,2,0,2,1,0,1,0.0,0,1
4,3,0,35.0,8.0500,3,1,1,7,0,1,0,1.0,0,1

In [22]:
X = df.drop(['alive'],axis = 1)

In [23]:
y = df['alive']

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=1)

In [25]:
from sklearn.linear_model import LogisticRegression

In [26]:
mod = LogisticRegression()
mod.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [27]:
pred = mod.predict(X_test)

In [28]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,pred)

0.7947761194029851

In [29]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,pred)

array([[133,  20],
       [ 35,  80]])