In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('Titanic_test.csv')

In [ ]:
df

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [ ]:
df1 = pd.read_csv('Titanic_train.csv')

In [ ]:
df1

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
datas = pd.concat([df,df1])

In [ ]:
datas

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
datas.isnull().sum()

PassengerId       0
Survived          0
Pclass            0
Name              0
Sex               0
Age             354
SibSp             0
Parch             0
Ticket            0
Fare              0
Cabin          1374
Embarked          4
dtype: int64

In [ ]:
datas = datas.drop('Cabin',axis=1)

In [ ]:
from sklearn.impute import SimpleImputer
si = SimpleImputer(strategy='mean')
datas['Age'] = si.fit_transform(datas[['Age']])
datas = datas.drop('Embarked',axis=1)

In [ ]:
datas.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
dtype: int64

In [ ]:
datas = datas.drop(['Name','Ticket'],axis=1)
datas

     PassengerId  Survived  Pclass     Sex        Age  SibSp  Parch     Fare
0              1         0       3    male  22.000000      1      0   7.2500
1              2         1       1  female  38.000000      1      0  71.2833
2              3         1       3  female  26.000000      0      0   7.9250
3              4         1       1  female  35.000000      1      0  53.1000
4              5         0       3    male  35.000000      0      0   8.0500
..           ...       ...     ...     ...        ...    ...    ...      ...
886          887         0       2    male  27.000000      0      0  13.0000
887          888         1       1  female  19.000000      0      0  30.0000
888          889         0       3  female  29.699118      1      2  23.4500
889          890         1       1    male  26.000000      0      0  30.0000
890          891         0       3    male  32.000000      0      0   7.7500

[1782 rows x 8 columns]

In [ ]:
threshold = 3
from scipy.stats import zscore
numerical_features = ['Fare','Age']
z_scores = np.abs(zscore(datas[numerical_features]))
print(z_scores)

[[0.85361623 0.90836068]
 [1.87608812 1.08289018]
 [0.84381645 0.41054797]
 ...
 [0.0255643  0.04981898]
 [0.39235618 0.41054797]
 [0.85361623 0.33617111]]

In [ ]:
outliers = np.where(z_scores > threshold)
print(outliers)

(array([], dtype=int64), array([], dtype=int64))

In [ ]:
from scipy.stats.mstats import winsorize
datas['Age'] = winsorize(datas['Age'],limits = (0.15,0.15))
datas['Fare'] = winsorize(datas['Fare'],limits = (0.15,0.15))

In [ ]:
object_cols = datas.select_dtypes(include='object').columns
display(object_cols)

Index(['Sex'], dtype='object')

In [ ]:
datas = pd.get_dummies(datas, columns=object_cols, drop_first=True)
display(datas.head())

   PassengerId  Survived  Pclass   Age  SibSp  Parch     Fare  Sex_male
0            1         0       3  22.0      1      0   7.7500      True
1            2         1       1  38.0      1      0  56.4958     False
2            3         1       3  26.0      0      0   7.9250     False
3            4         1       1  35.0      1      0  53.1000     False
4            5         0       3  35.0      0      0   8.0500      True

In [ ]:
datas['Sex_male'] = datas['Sex_male'].astype(int)
display(datas.head())

   PassengerId  Survived  Pclass   Age  SibSp  Parch     Fare  Sex_male
0            1         0       3  22.0      1      0   7.7500         1
1            2         1       1  38.0      1      0  56.4958         0
2            3         1       3  26.0      0      0   7.9250         0
3            4         1       1  35.0      1      0  53.1000         0
4            5         0       3  35.0      0      0   8.0500         1

In [ ]:
X = datas.drop(['Survived'],axis = 1)
y = datas['Survived']

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=1)

In [ ]:
from sklearn.ensemble import AdaBoostClassifier
ab =AdaBoostClassifier(n_estimators=20,learning_rate=0.7,random_state=1)
ab.fit(X_train,y_train)
y_pred = ab.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7663551401869159